# Generated by Django 5.2.17 on 2026-08-30 13:33

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=63, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=63, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, help_text='Можно оставить пустым, если отсутствует', max_length=63, verbose_name='Отчество')),
                ('position', models.CharField(blank=True, help_text='Например: директор, главный бухгалтер', max_length=127, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name', 'middle_name'],
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=127, verbose_name='Номер документа')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата документа')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Краткое содержание документа')),
                ('valid_from_date', models.DateField(default=django.utils.timezone.now, verbose_name='Действует с')),
                ('valid_to_date', models.DateField(default=datetime.datetime(9998, 12, 31, 21, 0, tzinfo=datetime.timezone.utc), verbose_name='Действует до')),
                ('status', models.CharField(choices=[('active', 'Действует'), ('modified', 'Изменён'), ('cancelled', 'Отменён')], default='active', max_length=20, verbose_name='Статус документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания в системе')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='doc_ctrl.doctype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-date', 'number'],
            },
        ),
        migrations.CreateModel(
            name='DocResponsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='Например: ответственный исполнитель, контролёр, согласующий', max_length=127, verbose_name='Роль')),
                ('is_indefinite', models.BooleanField(default=False, verbose_name='Бессрочно')),
                ('deadline', models.DateField(blank=True, help_text='Если срок не ограничен — оставьте пустым', null=True, verbose_name='Срок исполнения')),
                ('task', models.TextField(blank=True, null=True, verbose_name='Поручение')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='doc_ctrl.doc', verbose_name='Документ')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ords_as_responsible', to='doc_ctrl.person', verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Ответственный по документу',
                'verbose_name_plural': 'Ответственные по документу',
                'ordering': ['doc', 'person'],
            },
        ),
    ]
