# Generated by Django 5.2.17 on 2026-08-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_ctrl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctype',
            old_name='name',
            new_name='type',
        ),
    ]
