# Generated by Django 5.2.17 on 2026-09-10 13:24

import django.db.models.deletion
import doc_ctrl.models
import doc_ctrl.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_ctrl', '0002_rename_name_doctype_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=doc_ctrl.models.doc_file_path, validators=[doc_ctrl.validators.validate_doc_file], verbose_name='Файл документа')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='doc_ctrl.doc', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Файл документа',
                'verbose_name_plural': 'Файлы документов',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
